version: '3'
services:
  # MariaDB service
  db:
    image: yobasystems/alpine-mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sensor_data
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # Adminer service
  adminer:
    image: adminer:latest
    container_name: adminer_container
    ports:
      - "8080:8080"
    depends_on:
      - db
